library(tidyr)
library(dplyr)
library(ggplot2)
library(ggthemes)

data = read.csv(file = "Molecular_Weights_and_Emissions.csv", header = TRUE)
data = tbl_df(data)

TNO.data = select(data, TNO...MCM.species, Molecular.Weight.g.molecule, Emissions.molecules.cm.2.s.1)
TNO.data = rename(TNO.data, Species = TNO...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule, Emissions = Emissions.molecules.cm.2.s.1)
TNO.data$Speciation = rep("TNO", length(TNO.data$Species))
TNO.data = filter(TNO.data, !(Species == ""))
IPCC.data = select(data, IPCC...MCM.species, Molecular.Weight.g.molecule.1, Emissions.molecules.cm.2.s.1.1)
IPCC.data = rename(IPCC.data, Species = IPCC...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule.1, Emissions = Emissions.molecules.cm.2.s.1.1)
IPCC.data$Speciation = rep("IPCC", length(IPCC.data$Species))
IPCC.data = filter(IPCC.data, !(Species == ""))                                                                                                                                                                    
EMEP.data = select(data, EMEP...MCM.species, Molecular.Weight.g.molecule.2, Emissions.molecules.cm.2.s.1.2)
EMEP.data = rename(EMEP.data, Species = EMEP...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule.2, Emissions = Emissions.molecules.cm.2.s.1.2)
EMEP.data$Speciation = rep("EMEP", length(EMEP.data$Species))
EMEP.data = filter(EMEP.data, !(Species == ""))
DE94.data = select(data, DE94...MCM.species, Molecular.Weight.g.molecule.3, Emissions.molecules.cm.2.s.1.3)
DE94.data = rename(DE94.data, Species = DE94...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule.3, Emissions = Emissions.molecules.cm.2.s.1.3)
DE94.data$Speciation = rep("DE94", length(DE94.data$Species))
DE94.data = filter(DE94.data, !(Species == ""))
GR95.data = select(data, GR95...MCM.species, Molecular.Weight.g.molecule.4, Emissions.molecules.cm.2.s.1.4)
GR95.data = rename(GR95.data, Species = GR95...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule.4, Emissions = Emissions.molecules.cm.2.s.1.4) 
GR95.data$Speciation = rep("GR95", length(GR95.data$Species))
GR95.data = filter(GR95.data, !(Species == ""))
GR05.data = select(data, GR05...MCM.species, Molecular.Weight.g.molecule.5, Emissions.molecules.cm.2.s.1.5)
GR05.data = rename(GR05.data, Species = GR05...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule.5, Emissions = Emissions.molecules.cm.2.s.1.5)
GR05.data$Speciation = rep("GR05", length(GR05.data$Species))
GR05.data = filter(GR05.data, !(Species == ""))
UK98.data = select(data, UK98...MCM.species, Molecular.Weight.g.molecule.6, Emissions.molecules.cm.2.s.1.6)
UK98.data = rename(UK98.data, Species = UK98...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule.6, Emissions = Emissions.molecules.cm.2.s.1.6)
UK98.data$Speciation = rep("UK98", length(UK98.data$Species))
UK98.data = filter(UK98.data, !(Species == ""))
UK08.data = select(data, UK08...MCM.species, Molecular.Weight.g.molecule.7, Emissions.molecules.cm.2.s.1.7)
UK08.data = rename(UK08.data, Species = UK08...MCM.species, Molecular.Weight = Molecular.Weight.g.molecule.7, Emissions = Emissions.molecules.cm.2.s.1.7)
UK08.data$Speciation = rep("UK08", length(UK08.data$Species))
UK08.data = filter(UK08.data, !(Species == ""))
data = rbind(TNO.data, IPCC.data, EMEP.data, DE94.data, GR95.data, GR05.data, UK98.data, UK08.data)
data$Speciation = factor(data$Speciation, levels = c("TNO", "IPCC", "EMEP", "DE94", "GR95", "GR05", "UK98", "UK08"))

data = data %>% mutate(Bin.Factor = ifelse(Molecular.Weight < 40, "<40", ifelse(Molecular.Weight >= 40 & Molecular.Weight < 80, "40-80", ifelse(Molecular.Weight >= 80 & Molecular.Weight < 100, "80-100", ifelse(Molecular.Weight >= 100 & Molecular.Weight < 120, "100-120", ifelse(Molecular.Weight >= 120 & Molecular.Weight < 140, "120-140", ifelse(Molecular.Weight >= 140 & Molecular.Weight <180, "140-180", "other")))))))
data = data %>% arrange(desc(Bin.Factor))
data$Bin.Factor = factor(data$Bin.Factor, levels = rev(c("<40", "40-80", "80-100", "100-120", "120-140", "140-180")))

my.colours = c("<40" = "#62254f", "40-80" = "#f9c500", "80-100" = "#0e5628", "100-120" = "#ef6638", "120-140" = "#2b9eb3", "140-180" = "#b569b3")
               #"C8" = "#6db875", "C7" = "#0c3f78", "C6" = "#b569b3", "C5" = "#2b9eb3", "C4" = "#ef6638", "C3" = "#0e5628", "C2" = "#f9c500", "C1" = "#6c254f"
p = ggplot(data, aes(x = Speciation, y = Emissions, order = -as.numeric(Bin.Factor), group = Bin.Factor, fill = Bin.Factor)) 
p = p + geom_bar(stat = "identity")
p = p + scale_y_continuous(expand = c(0, 0)) + scale_x_discrete(expand = c(0, 0))
p = p + theme_tufte()
p = p + theme(axis.title.x = element_blank())
p = p + theme(axis.ticks.x = element_blank())
p = p + ylab("Emissions (molecules s-1 cm-2)")
p = p + theme(axis.line = element_line(colour = "black"))
p = p + scale_fill_manual(values = my.colours)
p

#pdf(file = "molecule_Emissions.pdf")
#print(p)
#dev.off()
