library(ggplot2)
library(tidyr)
library(dplyr)
library(ggthemes)

data = read.csv(file = "HOx_higher_alkanes_in_MCM_species.csv", header = TRUE)
data = tbl_df(data)

c6 = data %>% filter(Species == "CHEX" | Species == "M2PE" | Species == "M3PE" | Species == "NC6H14")
c6$C.number = rep(6, length(c6$Species))
c7 = data %>% filter(Species == "NC7H16" | Species == "M2HEX" | Species == "M3HEX")
c7$C.number = rep(7, length(c7$Mechanism))
c8 = data %>% filter(Species == "NC8H18")
c8$C.number = rep(8, length(c8$Mechanism))
c9 = data %>% filter(Species == "NC9H20")
c9$C.number = rep(9, length(c9$Mechanism))
c10 = data %>% filter(Species == "NC10H22")
c10$C.number = rep(10, length(c10$Mechanism))
c11 = data %>% filter(Species == "NC11H24")
c11$C.number = rep(11, length(c11$Mechanism))
c12 = data %>% filter(Species == "NC12H26")
c12$C.number = rep(12, length(c12$Mechanism))
higher.alkanes = rbind(c6, c7, c8, c9, c10, c11, c12)
higher.alkanes = higher.alkanes %>% group_by(Mechanism, Speciation, C.number) %>% summarise(Total.HOx = mean(HOx))
higher.alkanes = higher.alkanes %>% mutate(HOx.per.C = Total.HOx / C.number)

other.data = read.csv(file = "HOx_allocated_production_data.csv", header = TRUE, sep = ";")
other.data = tbl_df(other.data)
alkanes = other.data %>% filter(Category == "Ethane" | Category == "Propane" | Category == "Butanes" | Category == "Pentanes")
c2 = alkanes %>% filter(Category == "Ethane")
c2$C.number = rep(2, length(c2$HOx.Prod))
c3 = alkanes %>% filter(Category == "Propane")
c3$C.number = rep(3, length(c3$HOx.Prod))
c4 = alkanes %>% filter(Category == "Butanes")
c4$C.number = rep(4, length(c4$HOx.Prod))
c5 = alkanes %>% filter(Category == "Pentanes")
c5$C.number = rep(5, length(c5$HOx.Prod))
alks = rbind(c2, c3, c4, c5)
alks = alks %>% group_by(Mechanism, Speciation, C.number) %>% summarise(Total.HOx = mean(HOx.Prod))
alks = alks %>% mutate(HOx.per.C = Total.HOx / C.number)
alkanes = rbind(alks, higher.alkanes)

plot = ggplot(alkanes, aes(x = Mechanism, y = HOx.per.C)) + geom_point() + facet_grid(C.number ~ Speciation, scales = "free_y")
plot = plot + theme_bw()
plot = plot + theme(strip.text.y = element_text(angle = 0))
plot = plot + theme(strip.background = element_blank())
plot = plot + theme(axis.text.x = element_text(face = "bold", angle = 45, hjust = 0.7, vjust = 0.8))
plot = plot + theme(axis.title.x = element_blank())
plot = plot + theme(strip.text = element_text(face = "bold"))
plot = plot + ylab("Total HOx Production per Carbon Number (molecules (HOx) cm-3)")
plot = plot + theme(axis.title.y = element_text(face = "bold"))

pdf(file = "Alkanes_HOx_production_per_C.pdf", width = 10, height = 8)
print(plot)
dev.off()
